### ISSUE TITLE
ICM: Resources shall be set the default way in icm-web

### ISSUE THREAD

**Issue by khauser** [intershop/helm-charts#123]
The way it should look like:
```
resources:
  webadapter:
    limits:
      #cpu: 100m
      memory: 100Mi
    requests:
      #cpu: 100m
      memory: 100Mi
  agent:
    limits:
      #cpu: 100m
      memory: 200Mi
    requests:
      #cpu: 100m
      memory: 200Mi
```
