### ISSUE TITLE
ICM: icm-web ingress shall support multiple hosts 

### ISSUE THREAD

**Issue by khauser** [intershop/helm-charts#214]
This is the way IOM does it:
```
      hosts:
      - host: ${pwa_hostname}.pwa.intershop.de
        paths:
        - path: /
          pathType: ImplementationSpecific
      - host: int-live-connect.partner.com
        paths:
        - path: /
          pathType: ImplementationSpecific
```
