### ISSUE TITLE
ICM-WA: user defined certificate secret name not used anymore

### ISSUE THREAD

**Issue by Thomas-Bergmann** [intershop/helm-charts#375]
The values.yaml declares possible "secretName" which can be used at ingress configuration.
This value is ignored by the ssl-certificate-spc.yaml template. Instead the "certificateName" of the keyvault is used.

```
  sslCertificateRetrieval:
    enabled: false
    # secretName: <explicit-ssl-secret-name>
    keyvault:
      tenantId: <tenant-ID-of-the-KeyVault>
      subscriptionId: <subscription-ID-of-the-KeyVault>
      resourceGroup: <resource-group-of-the-KeyVault>
      keyvaultName: <name-of-the-KeyVault>
     certificateName: <name-of-certificate-at-keyvaul>
```
