### ISSUE TITLE
ICM: Enable dynamic environment keyvault secret exchange for customer projects

### ISSUE THREAD

**Issue by khauser** [intershop/helm-charts#531]
E.g.:
```
environmentsFromProjectSecrets:
- datadogLabel
- ebayKey
```

and
```
{{- range .Values.environmentsFromProjectSecrets }}
- name: {{.}}
  valueFrom:
    secretKeyRef:
      name: project-secrets
      key: {{.}}
{{- end -}}
```

This issue is connected to our internal infrastructure deployment (see #93578).
