### ISSUE TITLE
ICM: In case persistence.pagecache.type=emptyDir the separate WAA can't access the emptyDir of the WA.

### ISSUE THREAD

**Issue by Thomas-Bergmann** [intershop/helm-charts#785]
The helm values can configure emptyDir for pagecache. In that case the "emptyDir" of WA and WAA are different volumes. So the WAA can't invalidate the files of the page cache.

```yml
icm-web:
  persistence:
    pagecache:
      size: 1Gi
      type: emptyDir
```
